#!/bin/bash

files=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

# Check if $files is empty, and exit early with code 0 if true
if [ -z "$files" ]; then
    exit 0
fi

./src/vendor/bin/pint $files --test

# Check the exit code of the pint command
if [ $? -eq 0 ]; then
    exit 0
fi

./src/vendor/bin/pint --dirty
exit 1
