<?php

namespace Modules\Client\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Client\Entities\Client;
use Modules\Client\Entities\Pharmacy;
use Modules\Client\Enums\ClientType;

class ClientDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $client = Client::create([
            'name' => [
                'en' => 'El Ezaby',
                'ar' => 'العزبي',
            ],
            'type' => ClientType::BRAND,
            'code' => 'G1',
            'phone_number' => '0100200300',
        ]);

        $pharmacies = [
            [
                'name' => [
                    'en' => 'El Ezaby el harm',
                    'ar' => 'العزبي الهرم',
                ],
                'address' => 'شارع 9، الهرم قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'code' => 1,
                'phone_number' => '0100200300',
                'optional_phone_number' => '010020030040',
                'debt_limit' => 500000,
                'extra_discount' => 10,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'iterate_available_quantity' => rand(1, 4),
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'type' => 1,
                'delivery_id' => 10,
                'email' => 'ali@medical.com',
                'expiration_extra_discount' => '2023-09-30',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Ali',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 100,
                'minimum_target' => 50,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'balance' => 0,
                'call_shift' => 1,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'El Ezaby Faisel',
                    'ar' => 'العزبي فيصل',
                ],
                'address' => 'شارع 9، فيصل قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '01200200300',
                'optional_phone_number' => '0130020030040',
                'debt_limit' => 500000,
                'extra_discount' => 18,
                'discount_slat' => rand(0, 4),
                'iterate_available_quantity' => rand(1, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'code' => 2,
                'email' => 'andrew@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Andrew',
                'active' => false,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => random_int(100000, 999999),
                'minimum_target' => random_int(100000, 999999),
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 0,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'El Ezaby shobra masr',
                    'ar' => 'العزبي شبرا مصر',
                ],
                'address' => 'شارع 9، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '01400200300',
                'optional_phone_number' => '0150020030040',
                'debt_limit' => 500000,
                'extra_discount' => 9,
                'discount_slat' => rand(0, 4),
                'iterate_available_quantity' => rand(1, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 3,
                'type' => 1,
                'code' => 3,
                'email' => 'shasha@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Shasha',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200,
                'minimum_target' => 100,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'balance' => 0,
                'call_shift' => 2,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'El Ezaby el hegaz',
                    'ar' => 'العزبي الحجاز',
                ],
                'address' => 'شارع 9، الحجاز قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '01600200300',
                'optional_phone_number' => '0170020030040',
                'debt_limit' => 500000,
                'extra_discount' => 10,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 4,
                'email' => 'man3m@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Man3m',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 100000,
                'minimum_target' => 10000,
                'status' => rand(0, 2),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 4,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
        ];

        foreach ($pharmacies as $pharmacy) {
            $pharmacy = Pharmacy::create($pharmacy);
            $client->pharmacies()->attach($pharmacy);
        }

        //--------------------------------------

        $client = Client::create([
            'name' => [
                'en' => 'Ahmed shaker',
                'ar' => 'المندوب احمد شاكر',
            ],
            'type' => ClientType::SUPPLIER,
            'code' => 'G2',
        ]);

        $pharmacies = [
            [
                'name' => [
                    'en' => 'Hussen kamal pharmacy',
                    'ar' => 'صيدلية حسين كمال',
                ],
                'address' => 'شارع 1، الحجاز قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '01601200300',
                'optional_phone_number' => '0170220030040',
                'debt_limit' => 500000,
                'extra_discount' => 10,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 5,
                'email' => 'fielo@medical.com',
                'discount_slat' => rand(0, 4),
                'expiration_extra_discount' => '2023-09-30',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Fielo',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 1000000,
                'minimum_target' => 50000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 5,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'Mohammed and mohammed pharmacy',
                    'ar' => 'صيدلية محمد و محمد',
                ],
                'address' => 'شارع 9، المنيب قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '01803200300',
                'optional_phone_number' => '0190420030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 6,
                'email' => 'hader@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Hader',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 1000000,
                'minimum_target' => 50000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 3,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'Dr Walaa pharmacy',
                    'ar' => 'صيدلية دكتوره ولاء',
                ],
                'address' => 'شارع 2، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0120005200300',
                'optional_phone_number' => '012100620030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 7,
                'email' => 'sha3r@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Sha3r',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 1000000,
                'minimum_target' => 50000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 5,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
        ];

        foreach ($pharmacies as $pharmacy) {
            $pharmacy = Pharmacy::create($pharmacy);
            $client->pharmacies()->attach($pharmacy);
        }

        //--------------------------------------

        $client = Client::create([
            'name' => [
                'en' => 'Marko refaat',
                'ar' => 'المندوب ماركو رفعت',
            ],
            'type' => ClientType::SUPPLIER,
            'code' => 'G3',
        ]);

        $pharmacies = [
            [
                'name' => [
                    'en' => 'Dr Andrew khalil',
                    'ar' => 'صيدلية دكتور اندرو خليل',
                ],
                'address' => 'شارع 1، الرحاب، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0122001200300',
                'optional_phone_number' => '012300220030040',
                'debt_limit' => 500000,
                'extra_discount' => 10,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 8,
                'email' => 'ahmed@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Ahmed',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200000,
                'minimum_target' => 1000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 3,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'Elmahaba pharmacy',
                    'ar' => 'صيدلية المحبة',
                ],
                'address' => 'شارع 9، المنيب قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0124003200300',
                'optional_phone_number' => '012500420030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 9,
                'email' => 'ayman@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Ayman',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200000,
                'minimum_target' => 1000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 2,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'Elnoor pharmacy',
                    'ar' => 'صيدلية النور',
                ],
                'address' => 'شارع 2، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0126005200300',
                'optional_phone_number' => '012700620030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 10,
                'email' => 'kiro@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Kiro',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200000,
                'minimum_target' => 1000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 4,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
        ];

        foreach ($pharmacies as $pharmacy) {
            $pharmacy = Pharmacy::create($pharmacy);
            $client->pharmacies()->attach($pharmacy);
        }

        //--------------------------------------

        $client = Client::create([
            'name' => [
                'en' => '19011',
                'ar' => '19011',
            ],
            'type' => ClientType::SUPPLIER,
            'code' => 'G4',
        ]);

        $pharmacies = [
            [
                'name' => [
                    'en' => '19011 dokii',
                    'ar' => '19011 الدقي',
                ],
                'address' => 'شارع 1، الرحاب، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0129001200300',
                'optional_phone_number' => '013000220030040',
                'debt_limit' => 500000,
                'extra_discount' => 10,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 11,
                'email' => 'adham@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Adham',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200000,
                'minimum_target' => 1000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 5,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => '19011 Mohandeseen',
                    'ar' => '19011 المهندسين',
                ],
                'address' => 'شارع 9، المنيب قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0131003200300',
                'optional_phone_number' => '013200420030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 12,
                'email' => 'fady@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'fady',
                'active' => false,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 1000000,
                'minimum_target' => 5000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 4,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => '19011 Zamalek',
                    'ar' => '19011 الزمالك',
                ],
                'address' => 'شارع 2، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0133005200300',
                'optional_phone_number' => '013400620030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 13,
                'email' => 'yasser@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'yasser',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200000,
                'minimum_target' => 1000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 3,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'ar' => '19011 امبابه',
                    'en' => '19011 Embabah',
                ],
                'address' => 'شارع 2، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0135005200300',
                'optional_phone_number' => '013600620030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 14,
                'email' => 'khalil@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'khalil',
                'active' => false,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 10000,
                'minimum_target' => 5000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 1,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
        ];
        foreach ($pharmacies as $pharmacy) {
            $pharmacy = Pharmacy::create($pharmacy);
            $client->pharmacies()->attach($pharmacy);
        }

        //--------------------------------------

        $client = Client::create([
            'name' => [
                'en' => 'El Saidaly',
                'ar' => 'الصيدلي',
            ],
            'type' => ClientType::SUPPLIER,
            'code' => 'G5',
        ]);

        $pharmacies = [
            [
                'name' => [
                    'en' => 'El Esaaf Pharmacy',
                    'ar' => 'صيدليه الاسعاف',
                ],
                'address' => 'ميدان الاسعاف، قسم الجيزة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '013702030',
                'debt_limit' => 200000,
                'extra_discount' => 5,
                'discount_slat' => rand(0, 4),
                'optional_phone_number' => '0138002003004',
                'latitude' => 30.010841112363025,
                'longitude' => 31.209571824041205,
                'track_id' => 2,
                'city_id' => 1,
                'area_id' => 3,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 15,
                'email' => 'fakhr@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'fakhr',
                'active' => false,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 10000,
                'minimum_target' => 5000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 4,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'Mostafa elseedy pharmacy',
                    'ar' => 'صيدلية دكتور مصطفى الصعيدي',
                ],
                'address' => 'شارع 9، المنيب قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0139003200300',
                'optional_phone_number' => '01400420030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 16,
                'email' => 'ali1@hotmail.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Ali',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 200000,
                'minimum_target' => 1000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 6,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'Marko saaed pharmacy pharmacy',
                    'ar' => 'صيدلية دكتور ماركو سعيد',
                ],
                'address' => 'شارع 2، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0141005200300',
                'optional_phone_number' => '014200620030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 17,
                'email' => 'ali99@hotmail.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Ali',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 10000,
                'minimum_target' => 5000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 1,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
            [
                'name' => [
                    'en' => 'El Saidaly fifth square',
                    'ar' => 'الصيدلي التجمع الخامس',
                ],
                'address' => 'شارع 2، شبرا مصر قسم الخليفة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '0143005200300',
                'optional_phone_number' => '014400620030040',
                'debt_limit' => 500000,
                'extra_discount' => 8,
                'discount_slat' => rand(0, 4),
                'latitude' => 30.013530329568773,
                'longitude' => 31.296284507514617,
                'track_id' => 1,
                'city_id' => 1,
                'area_id' => 2,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 18,
                'email' => 'ali11@hotmail.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Ali',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 10000,
                'minimum_target' => 5000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'note' => 'ملاحظات على الصيدلية',
                'balance' => 0,
                'call_shift' => 1,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
        ];

        foreach ($pharmacies as $pharmacy) {
            $pharmacy = Pharmacy::create($pharmacy);
            $client->pharmacies()->attach($pharmacy);
        }

        //--------------------------------------

        $client = Client::create([
            'name' => [
                'en' => 'Awny Group',
                'ar' => 'مجموعة عوني',
            ],
            'type' => ClientType::BRAND,
            'code' => 'G6',
        ]);

        $pharmacies = [
            [
                'name' => [
                    'en' => 'Awny Pharmacy',
                    'ar' => 'صيدليه عوني',
                ],
                'address' => 'ميدان الاسعاف، قسم الجيزة، محافظة القاهرة',
                'payment_type' => rand(0, 12),
                'phone_number' => '013702036050',
                'debt_limit' => 200000,
                'extra_discount' => 5,
                'discount_slat' => rand(0, 4),
                'optional_phone_number' => '01380020004',
                'latitude' => 30.010841112363025,
                'longitude' => 31.209571824041205,
                'track_id' => 2,
                'city_id' => 1,
                'area_id' => 3,
                'type' => 1,
                'iterate_available_quantity' => rand(1, 4),
                'code' => 19,
                'email' => 'awny@medical.com',
                'expiration_extra_discount' => '2023-09-10',
                'minimum_for_extra_discount' => 1000,
                'doctor' => 'Awny',
                'active' => true,
                'commercial_registration_no' => random_int(100000, 999999),
                'license_no' => random_int(100000, 999999),
                'tax_card_no' => random_int(100000, 999999),
                'target' => 10000,
                'minimum_target' => 5000,
                'status' => rand(0, 2),
                'payment_period' => rand(0, 4),
                'delivery_id' => 10,
                'balance' => 0,
                'call_shift' => 4,
                'all' => rand(7, 30),
                'follow_up' => rand(0, 1),
            ],
        ];

        foreach ($pharmacies as $pharmacy) {
            $pharmacy = Pharmacy::create($pharmacy);
            $client->pharmacies()->attach($pharmacy);
        }
    }
}
